msm8916-common: remove ro.adb.secure prop because it's not allowed in userdebug build.
Compiler complains if we build an userdebug build with

error: found duplicate sysprop assignments:
ro.adb.secure=1
ro.adb.secure=0

However, having this prop left in works for eng builds.