msm8916-common: [TEMP] comment out libinit_msm8916_base
"system/core/base/include" is removed from Android 12, so let's
comment this out and remove this altogether for now

Compiler says
error: device/samsung/msm8916-common/init/Android.bp:26:1:
module "libinit_msm8916_base" variant "android_arm_armv8-a_static":
source path "system/core/base/include" does not exist
14:35:40 soong bootstrap failed with: exit status 1